trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'abel-new-service-conn'
  resourceGroupName: 'abel_RG'
  location: 'westeurope'

steps:

  # Install Terraform
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: '1.5.7'

  # Terraform Init
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-task.TerraformTaskV2@2
    displayName: 'Terraform Init'
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      environmentServiceNameAzureRM: $(azureServiceConnection)

  # Terraform Plan
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-task.TerraformTaskV2@2
    displayName: 'Terraform Plan'
    inputs:
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      environmentServiceNameAzureRM: $(azureServiceConnection)

  # Terraform Apply
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-task.TerraformTaskV2@2
    displayName: 'Terraform Apply'
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      environmentServiceNameAzureRM: $(azureServiceConnection)
      commandOptions: '-auto-approve'
