trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'abel-new-service-conn'
  resourceGroupName: 'abel_RG'
  location: 'westeurope'

steps:

  # Install Terraform
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.5.7'

  # Terraform Init (uses backend.tf)
  - task: TerraformCLI@1
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      environmentServiceName: $(azureServiceConnection)

  # Terraform Plan
  - task: TerraformCLI@1
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      environmentServiceName: $(azureServiceConnection)

  # Terraform Apply
  - task: TerraformCLI@1
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      environmentServiceName: $(azureServiceConnection)
      args: '-auto-approve'
